### ISSUE TITLE
otto crash at startup

### ISSUE THREAD

**Issue by stfnndrsn** [hashicorp/otto#357]
Hey,

When I'm running two otto instances; a PHP and a MySQL it seems otto crashes at startup

```
$ otto dev ssh 
unexpected fault address 0x0
fatal error: fault
[signal 0x7 code=0x80 addr=0x0 pc=0x40dcbb]

goroutine 1 [running, locked to thread]:
runtime.throw(0xaaa048, 0x5)
	/Users/mitchellh/code/3rdparty/go/src/runtime/panic.go:527 +0x90 fp=0xc820041da8 sp=0xc820041d90
runtime.sigpanic()
	/Users/mitchellh/code/3rdparty/go/src/runtime/sigpanic_unix.go:21 +0x10c fp=0xc820041df8 sp=0xc820041da8
runtime.makemap(0x8fbf00, 0x0, 0x0, 0x0, 0xc82000e210)
	/Users/mitchellh/code/3rdparty/go/src/runtime/hashmap.go:188 +0x3b fp=0xc820041e58 sp=0xc820041df8
syscall.init()
	/Users/mitchellh/code/3rdparty/go/src/syscall/syscall_linux.go:910 +0x1e3 fp=0xc820041ea0 sp=0xc820041e58
os.init()
	/Users/mitchellh/code/3rdparty/go/src/os/types_notwin.go:25 +0x4c fp=0xc820041ee8 sp=0xc820041ea0
fmt.init()
	/Users/mitchellh/code/3rdparty/go/src/fmt/scan.go:1195 +0x56 fp=0xc820041f48 sp=0xc820041ee8
main.init()
	/Users/mitchellh/code/go/src/github.com/hashicorp/otto/version.go:12 +0x3f fp=0xc820041f50 sp=0xc820041f48
runtime.main()
	/Users/mitchellh/code/3rdparty/go/src/runtime/proc.go:100 +0x27f fp=0xc820041fa0 sp=0xc820041f50
runtime.goexit()
	/Users/mitchellh/code/3rdparty/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820041fa8 sp=0xc820041fa0
```

[MySQL Appfile.txt](https://github.com/hashicorp/otto/files/49638/MySQL.Appfile.txt)
[Appfile.txt](https://github.com/hashicorp/otto/files/49639/Appfile.txt)

**Comment by mitchellh** [comment]
This looks like a Go bug. I can't reproduce it here locally. Let's try the next version and see if it goes away. If not, open a new issue. Sorry! The fatal is coming out of Go and this is the only place I've ever seen this error.

**Comment by kenorb** [comment]
It may be related to presence of Websense kernel module, see: mitchellh/vagrant/issues/6914
