### ISSUE TITLE
Python base image should include libmysqlclient-dev

### ISSUE THREAD

**Issue by apeace** [hashicorp/otto#400]
I have a Python app with a dependency: `mysqlclient==1.3.6`. When I `otto dev ssh` into my VM, and run `pip install -r requirements.txt`, I get this error:

```
Collecting mysqlclient==1.3.6 (from -r requirements.txt (line 35))
  Using cached mysqlclient-1.3.6.tar.gz
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-EIKUK9/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 47, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
```

Since MySQL is commonly used with Python apps, I suggest that `libmysqlclient-dev` be included in the base image for the Python app type.

If I am wrong, is there another solution I should be using? I have looked through the docs and I'm not finding a hook for me to specify that Otto run a command like "apt-get install".

**Comment by jmetzmeier** [comment]
There was work done to solve this type of problem for Ruby gems. We should look at trying to replicate that for Python.

**Comment by xarg** [comment]
I'm using postgres and never expect having `libpq-dev` by default. I'm sure people who use mongo have some deps as well. If this were open to vote I would vote against adding this dep.

**Comment by apeace** [comment]
@xarg that's understandable. Maybe the solution @jmetzmeier alluded to is what's really needed, I'm just not sure what that is.

**Comment by maxnordlund** [comment]
I also think treating a certain database specially would be odd, to say the least. I think something like [gem.sh][1] would be a better solution. This also helps keep the size down for those that don't need/use mysql/postgres/mongo etc.

[1]: https://github.com/hashicorp/otto/blob/877e943d5c2f0e73db7073cdc02a2809d388785d/builtin/scriptpack/ruby/data/gem.sh
