### ISSUE TITLE
`template_path': undefined method `directory' for nil:NilClass 

### ISSUE THREAD

**Issue by ragusource** [hashicorp/otto#462]
$ otto dev
==> Creating development environment layers...
    Otto uses layers to speed up building development environments.
    Each layer only needs to be built once. We've detected that the
    layers below aren't created yet. These will be built this time.
    Future development envirionments will use the cached versions
    to be much, much faster.
==> Verifying created layer: consul
==> Creating layer: consul
Bringing machine 'default' up with 'parallels' provider...
==> default: Importing base box 'parallels/ubuntu-12.04'...
==> default: Setting the default configuration for VM...
==> default: Setting the name of the VM: consul_default_1457698812087_65678
==> default: Preparing network interfaces based on configuration...
    default: Adapter 0: shared
==> default: Clearing any previously set network interfaces...
==> default: Forwarding ports...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 10.211.55.30:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for Parallels Tools installed on the VM...
==> default: Parallels Tools installed on this VM are outdated! In most cases
==> default: this is fine but in rare cases it can cause things such as shared
==> default: folders to not work properly. If you see shared folder errors,
==> default: please update Parallels Tools within the virtual machine and
==> default: reload your VM.
==> default: Mounting shared folders...
    default: /otto/foundation-layer-consul => /Users/rrajaratnam/SPIDEROAK/development/sourcier/react/psadmin/.otto/compiled/app/foundation-consul/app-dev
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: [otto] Installing Consul...
==> default: [otto] Installing dnsmasq for Consul...
==> default: Attempting graceful shutdown of VM...
==> Creating layer: node5.5.0
Bringing machine 'default' up with 'parallels' provider...
/Users/rrajaratnam/.vagrant.d/gems/gems/vagrant-parallels-1.5.0/lib/vagrant-parallels/action/import.rb:73:in `template_path': undefined method `directory' for nil:NilClass (NoMethodError)
	from /Users/rrajaratnam/.vagrant.d/gems/gems/vagrant-parallels-1.5.0/lib/vagrant-parallels/action/import.rb:45:in `recover'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:67:in `block in recover'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:64:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:64:in `recover'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:61:in `recover'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:67:in `block in recover'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:64:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:64:in `recover'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:53:in `rescue in call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:28:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:224:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:199:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
Error building dev environment: Error building dev environment layers: Error executing Vagrant: exit status 1

The error messages from Vagrant are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.

**Comment by leowmjw** [comment]
@ragusource; looking at your output, I presume your Vagrant Parallels is v1.5.0?  If so; note that Otto requires Vagrant to be >=1.8 and it is not compatible with vagrant-parallels <=1.6 

See the note in:
https://github.com/Parallels/vagrant-parallels/releases/tag/v1.6.0

Maybe that is the problem?  Try to update your vagrant-parallels; and try agin.

**Comment by ragusource** [comment]
@leowmjw 

$ vagrant --version
Vagrant 1.8.1
rrajaratnam at Rogers-MacBook-Pro in ~
$ vagrant plugin list
vagrant-parallels (1.5.0)
vagrant-share (1.1.5, system)
rrajaratnam at Rogers-MacBook-Pro in ~

I am on vagrant 1.8.1 with vagrant-parallels 1.5.0, I did try upgrading the version by doing this:

$ vagrant plugin update vagrant-parallels
Updating plugins: vagrant-parallels. This may take a few minutes...
All plugins are up to date.
rrajaratnam at Rogers-MacBook-Pro in ~

Shall I raise that as an issue with vagrant? I will manually upgrade and try again.

**Comment by ragusource** [comment]
@leowmjw running vagrant plugin install vagrant-parallels updated me to version 1.6.1, however I am still getting the following:

$ otto compile
==> Loading Appfile...
==> No Appfile found! Detecting project information...
    No Appfile was found. If there is no Appfile, Otto will do its best
    to detect the type of application this is and set reasonable defaults.
    This is a good way to get started with Otto, but over time we recommend
    writing a real Appfile since this will allow more complex customizations,
    the ability to reference dependencies, versioning, and more.
==> Fetching all Appfile dependencies...
==> Compiling...
    Application:    psadmin (node)
    Project:        psadmin
    Infrastructure: aws (simple)

    Compiling infra...
    Compiling foundation: consul
==> Compiling main application...
==> Compilation success!
    This means that Otto is now ready to start a development environment,
    deploy this application, build the supporting infrastructure, and
    more. See the help for more information.

    Supporting files to enable Otto to manage your application from
    development to deployment have been placed in the output directory.
    These files can be manually inspected to determine what Otto will do.
rrajaratnam at Rogers-MacBook-Pro in ~/SPIDEROAK/development/sourcier/react/psadmin
$ otto dev --debug
==> Creating development environment layers...
    Otto uses layers to speed up building development environments.
    Each layer only needs to be built once. We've detected that the
    layers below aren't created yet. These will be built this time.
    Future development envirionments will use the cached versions
    to be much, much faster.
==> Verifying created layer: consul
==> Creating layer: consul
Bringing machine 'default' up with 'parallels' provider...
==> default: Registering VM image from the base box 'parallels/ubuntu-12.04'...
==> default: Creating new virtual machine as a linked clone...
==> default: Unregistering the box VM image...
==> default: Setting the default configuration for VM...
==> default: Setting the name of the VM: consul_default_1457954729144_32236
==> default: Preparing network interfaces based on configuration...
    default: Adapter 0: shared
==> default: Clearing any previously set network interfaces...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 10.211.55.35:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for Parallels Tools installed on the VM...
==> default: Parallels Tools installed on this VM are outdated! In most cases
==> default: this is fine but in rare cases it can cause things such as shared
==> default: folders to not work properly. If you see shared folder errors,
==> default: please update Parallels Tools within the virtual machine and
==> default: reload your VM.
==> default: Mounting shared folders...
    default: /otto/foundation-layer-consul => /Users/rrajaratnam/SPIDEROAK/development/sourcier/react/psadmin/.otto/compiled/app/foundation-consul/app-dev
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: [otto] Installing Consul...
==> default: [otto] Installing dnsmasq for Consul...
==> default: Attempting graceful shutdown of VM...
==> Creating layer: node4.1.0
Bringing machine 'default' up with 'parallels' provider...
The clone environment hasn't been created yet. To clone from
another Vagrantfile, it must already be created with `vagrant up`.
It doesn't need to be running.

Additionally, the created environment must be started with a provider
matching this provider. For example, if you're using VirtualBox,
the clone environment must also be using VirtualBox.
Error building dev environment: Error building dev environment layers: Error executing Vagrant: exit status 1

The error messages from Vagrant are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.

**Comment by ragusource** [comment]
@leowmjw I have noticed that, when this this happens:

==> default: Attempting graceful shutdown of VM...

The virtual machine is getting destroyed.

**Comment by leowmjw** [comment]
@ragusource The VM is getting destroyed as part of Otto's clean up process when it encounters any problem.

So it seems your original problem is solved.  Your current problem looks similar to https://github.com/hashicorp/otto/issues/420.

You can probably try setting Vagrant's ENV VAGRANT_DEFAULT_PROVIDER to match Parallels:
```
$ VAGRANT_DEFAULT_PROVIDER=parallels otto dev
```

**Comment by ragusource** [comment]
@leowmjw I already have this variable set in my environment:

$ echo $VAGRANT_DEFAULT_PROVIDER
parallels

I have tried what you have suggested anyway, here is the output:

$ VAGRANT_DEFAULT_PROVIDER=parallels otto dev
==> Creating development environment layers...
    Otto uses layers to speed up building development environments.
    Each layer only needs to be built once. We've detected that the
    layers below aren't created yet. These will be built this time.
    Future development envirionments will use the cached versions
    to be much, much faster.
==> Creating layer: consul
Bringing machine 'default' up with 'parallels' provider...
==> default: Registering VM image from the base box 'parallels/ubuntu-12.04'...
==> default: Creating new virtual machine as a linked clone...
==> default: Unregistering the box VM image...
==> default: Setting the default configuration for VM...
==> default: Setting the name of the VM: consul_default_1457977616140_28817
==> default: Preparing network interfaces based on configuration...
    default: Adapter 0: shared
==> default: Clearing any previously set network interfaces...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 10.211.55.40:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for Parallels Tools installed on the VM...
==> default: Parallels Tools installed on this VM are outdated! In most cases
==> default: this is fine but in rare cases it can cause things such as shared
==> default: folders to not work properly. If you see shared folder errors,
==> default: please update Parallels Tools within the virtual machine and
==> default: reload your VM.
==> default: Mounting shared folders...
    default: /otto/foundation-layer-consul => /Users/rrajaratnam/SPIDEROAK/development/sourcier/react/psadmin/.otto/compiled/app/foundation-consul/app-dev
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: [otto] Installing Consul...
==> default: [otto] Installing dnsmasq for Consul...
==> default: Attempting graceful shutdown of VM...
==> Creating layer: ruby2.2
Bringing machine 'default' up with 'parallels' provider...
The clone environment hasn't been created yet. To clone from
another Vagrantfile, it must already be created with `vagrant up`.
It doesn't need to be running.

Additionally, the created environment must be started with a provider
matching this provider. For example, if you're using VirtualBox,
the clone environment must also be using VirtualBox.
Error building dev environment: Error building dev environment layers: Error executing Vagrant: exit status 1

The error messages from Vagrant are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.

**Comment by leowmjw** [comment]
@ragusource Unfortunately I am out of ideas :(

You probably want to gather the Vagrant debug log fully like below and post a gist for Hashicorp folks to look at:
```
$ VAGRANT_DEFAULT_PROVIDER=parallels VAGRANT_LOG=debug OTTO_LOG=1 otto dev
```

**Comment by legal90** [comment]
@ragusource 

>$ vagrant plugin list
vagrant-parallels (1.5.0)
vagrant-share (1.1.5, system)

>$ vagrant plugin update vagrant-parallels
Updating plugins: vagrant-parallels. This may take a few minutes...
All plugins are up to date.

That looks really strange. There are newer versions available. Try to reinstall the plugin:

```
vagrant plugin uninstall vagrant-parallels && vagrant plugin install vagrant-parallels
```

Then try it from the scratch:
```
otto dev layers --prune
otto dev destroy
VAGRANT_DEFAULT_PROVIDER=parallels otto dev
```
